export const MAIN_NAVIGATION = [
  {
    label: 'About',
    href: '/about',
    children: [
      { label: 'Overview', href: '/about' },
      { label: 'Leadership', href: '/about/leadership' },
      { label: 'Vision & Mission', href: '/about/vision-mission' },
      { label: 'Awards & Recognition', href: '/about/awards' },
      { label: 'Accreditation', href: '/about/accreditation' },
    ],
  },
  {
    label: 'Academics',
    href: '/academics',
    children: [
      { label: 'Departments', href: '/academics/departments' },
      { label: 'Programs', href: '/academics/programs' },
      { label: 'Faculty', href: '/academics/faculty' },
      { label: 'Research', href: '/academics/research' },
    ],
  },
  {
    label: 'Admissions',
    href: '/admissions',
    children: [
      { label: 'How to Apply', href: '/admissions/how-to-apply' },
      { label: 'Fee Structure', href: '/admissions/fee-structure' },
      { label: 'Scholarships', href: '/admissions/scholarships' },
      { label: 'International Students', href: '/admissions/international' },
    ],
  },
  {
    label: 'Campus Life',
    href: '/campus-life',
    children: [
      { label: 'Facilities', href: '/campus-life/facilities' },
      { label: 'Clubs & Activities', href: '/campus-life/clubs' },
      { label: 'Events', href: '/campus-life/events' },
      { label: 'Gallery', href: '/campus-life/gallery' },
    ],
  },
  {
    label: 'Placements',
    href: '/placements',
    children: [
      { label: 'Statistics', href: '/placements/statistics' },
      { label: 'Our Recruiters', href: '/placements/recruiters' },
      { label: 'Success Stories', href: '/placements/testimonials' },
    ],
  },
  {
    label: 'Contact',
    href: '/contact',
  },
];

export const QUICK_ACCESS = {
  prospectiveStudents: [
    { label: 'View Programs', href: '/academics/programs' },
    { label: 'Apply Now', href: '/admissions/how-to-apply' },
    { label: 'Fee Structure', href: '/admissions/fee-structure' },
    { label: 'Virtual Tour', href: '/campus-life/gallery' },
  ],
  currentStudents: [
    { label: 'Student Portal', href: '/student-portal' },
    {
      label: 'Exam Results',
      href: 'http://webresults.chaitanya.edu.in',
      external: true,
    },
    { label: 'Time Tables', href: '/student-portal#timetables' },
    { label: 'Library', href: '/campus-life/facilities#library' },
  ],
  parents: [
    { label: 'Fee Payment', href: '/admissions/fee-structure' },
    { label: 'Contact Us', href: '/contact' },
    { label: 'Campus Facilities', href: '/campus-life/facilities' },
  ],
};

export const DEPARTMENTS = [
  // Engineering Departments
  {
    id: 'cse',
    name: 'Computer Science & Engineering',
    shortName: 'CSE',
    description: 'Cutting-edge programs in AI, ML, Data Science, and Software Engineering.',
    programs: 8,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop&q=80',
    slug: 'computer-science-engineering',
    email: 'hod.cse@chaitanya.edu.in',
    recognition: ['UGC', 'AICTE'],
    yearEstablished: 2008,
  },
  {
    id: 'ece',
    name: 'Electronics & Communication Engineering',
    shortName: 'ECE',
    description: 'Advanced studies in VLSI Design, Wireless Communication, 5G/6G Technologies, and Embedded Systems.',
    programs: 6,
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&h=600&fit=crop&q=80',
    slug: 'electronics-communication',
    email: 'hod.ece@chaitanya.edu.in',
    phone: '8341623087',
    recognition: ['AICTE', 'UGC'],
    yearEstablished: 2010,
    labs: [
      'Electronic Devices & Circuits Lab',
      'Digital System Design Lab',
      'Analog Electronic Circuits Lab',
      'Microprocessors & Microcontrollers Lab',
      'Linear Integrated Circuits Lab',
      'Analog & Digital Communication Lab',
      'Digital Signal Processing Lab',
      'Microwave Engineering Lab',
    ],
    researchAreas: [
      'VLSI Design & Nanoelectronics',
      'Antenna Engineering',
      'Wireless Communication & 5G/6G Technologies',
      'Digital Signal Processing',
      'AI, ML & Deep Learning Applications',
      'Embedded Systems & IoT',
      'Image Processing & Computer Vision',
    ],
  },
  {
    id: 'eee',
    name: 'Electrical & Electronics Engineering',
    shortName: 'EEE',
    description: 'Programs in Power Systems, Power Electronics, Smart Grid, and Advanced Electrical Drives.',
    programs: 4,
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?w=800&h=600&fit=crop&q=80',
    slug: 'electrical-electronics',
    email: 'hod.eee@chaitanya.edu.in',
    phone: '9701667681',
    recognition: ['UGC', 'AICTE'],
    labs: [
      'Basic Electrical Engineering Lab',
      'Network Theory Lab',
      'Electrical Machines-I & II Lab',
      'Linear Control Systems Lab',
      'Power Electronics Lab',
      'Power Systems Lab',
      'Electrical Measurements Lab',
      'Electrical Simulation Lab',
    ],
    researchAreas: [
      'Power Systems',
      'Power Electronics',
      'Smart Grid',
      'Advanced Electrical Drives',
      'Control Systems',
      'Power Systems with AI and ML',
    ],
  },
  {
    id: 'civil',
    name: 'Civil Engineering',
    shortName: 'CIVIL',
    description: 'Programs in Structural Engineering, Geotechnical Engineering, and Sustainable Construction.',
    programs: 4,
    image: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=800&h=600&fit=crop&q=80',
    slug: 'civil-engineering',
    email: 'hod.civ@chaitanya.edu.in',
    phone: '9010070404',
    recognition: ['UGC', 'AICTE'],
    labs: [
      'Computer Aided Civil Engineering Lab',
      'Fluid Mechanics Lab',
      'Construction Material Testing Lab',
      'Engineering Geology Lab',
      'Surveying & Geomatics Lab',
      'Hydraulic Engineering Lab',
      'Concrete Technology Lab',
      'Geo Technical Engineering Lab',
      'Environmental Engineering Lab',
    ],
    researchAreas: [
      'Sustainable and Green Construction Materials',
      'Concrete Technology and Durability Studies',
      'Structural Health Monitoring',
      'Earthquake Engineering',
      'Transportation Planning',
      'Water Resources Engineering',
      'Smart Cities and Infrastructure',
      'Building Information Modeling (BIM)',
    ],
  },
  {
    id: 'mechanical',
    name: 'Mechanical Engineering',
    shortName: 'MECH',
    description: 'Programs in Design, Manufacturing, Thermal Sciences, Robotics, and Automation.',
    programs: 4,
    image: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&h=600&fit=crop&q=80',
    slug: 'mechanical-engineering',
    email: 'hod.mec@chaitanya.edu.in',
    phone: '9776349951',
    recognition: ['AICTE'],
    labs: [
      'Thermodynamics Lab',
      'Manufacturing Technology Lab I & II',
      'Strength of Material Lab',
      'Machine Drawing Practice Lab',
      'Internal Combustion Engine Lab',
      'Fluid Mechanics and Hydraulics Lab',
      'Heat Transfer Lab',
      'Design of Machine Elements Lab',
      'Physical Metallurgy Lab',
    ],
    researchAreas: [
      'Design and Analysis',
      'Manufacturing and Production Engineering',
      'Thermal and Fluid Sciences',
      'Mechatronics, Robotics, and Automation',
      'Materials and Metallurgy',
      'Energy and Sustainability',
      'AI and Computational Applications',
    ],
  },
  // Pharmacy
  {
    id: 'pharmacy',
    name: 'Pharmacy',
    shortName: 'PHARM',
    description: 'PCI approved B.Pharm, M.Pharm, Pharm.D programs with 32 specialized laboratories.',
    programs: 6,
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=600&fit=crop&q=80',
    slug: 'pharmacy',
    email: 'pharmacy@chaitanyacolleges.com',
    phone: '9948172444',
    recognition: ['PCI'],
    yearEstablished: 2008,
    labs: [
      'Pharmaceutics Lab I & II',
      'Pharmaceutical Inorganic Chemistry',
      'Pharmaceutical Organic Chemistry',
      'Pharmaceutical Analysis Lab',
      'Pharmacognosy Lab I & II',
      'Pharmacology Lab I & II',
      'Human Anatomy and Physiology Lab',
      'Pharmaceutical Biotechnology Lab',
      'Central Instrumentation Lab',
      'Clinical Pharmacy Lab',
      'Hospital Pharmacy',
      'Model Pharmacy Lab',
      'Animal House',
    ],
    fees: {
      'B.Pharmacy': '₹1,10,000/year',
      'Pharm.D': '₹2,00,000/year',
      'M.Pharmacy': '₹1,10,000/year',
    },
  },
  // Allied Health Sciences
  {
    id: 'physiotherapy',
    name: 'Physiotherapy',
    shortName: 'BPT',
    description: 'IAP and NCAHP recognized Bachelor of Physiotherapy with specialized rehabilitation training.',
    programs: 1,
    image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop&q=80',
    slug: 'physiotherapy',
    email: 'hod.physiotherapy@chaitanya.edu.in',
    recognition: ['IAP', 'NCAHP'],
    yearEstablished: 2023,
    labs: [
      'Anatomy Lab',
      'Physiology Lab',
      'Biomechanics Lab',
      'Exercise Therapy Lab',
      'Electrotherapy Lab',
      'Out Patient Department',
    ],
    researchAreas: [
      'Musculoskeletal Rehabilitation',
      'Neurological Rehabilitation',
      'Cardiothoracic Rehabilitation',
      'Sports Sciences',
    ],
    fees: {
      'BPT': '₹1,20,000/year',
    },
  },
  {
    id: 'mlt',
    name: 'Medical Lab Technology',
    shortName: 'MLT',
    description: 'UGC recognized BSc MLT program with specialized diagnostic laboratory training.',
    programs: 1,
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=800&h=600&fit=crop&q=80',
    slug: 'medical-lab-technology',
    email: 'lathahod@chaitanya.edu.in',
    recognition: ['UGC'],
    labs: [
      'Haematology Lab',
      'Histopathology Lab',
      'Bacteriology Lab',
      'Pathology Lab',
      'Microbiology Lab',
    ],
    researchAreas: [
      'Blood Banking and Transfusion Medicine',
      'Molecular Diagnostics',
      'Cytology and Histology',
      'Microbiology',
    ],
  },
  {
    id: 'radiology',
    name: 'Radiology & Imaging Technology',
    shortName: 'RIT',
    description: 'NCAHP and AERB recognized program with advanced imaging technology labs.',
    programs: 1,
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&h=600&fit=crop&q=80',
    slug: 'radiology-imaging',
    recognition: ['NCAHP', 'AERB', 'UGC'],
    labs: [
      'X-Ray Lab',
      'CT Lab',
      'MRI Lab',
      'Mammography Lab',
      'Fluoroscopy Lab',
      'USG Lab',
    ],
  },
  // Sciences
  {
    id: 'biochemistry',
    name: 'Biochemistry',
    shortName: 'BIOCHEM',
    description: 'UGC recognized programs with focus on Molecular Biology, Enzymology, and Clinical Biochemistry.',
    programs: 2,
    image: 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800&h=600&fit=crop&q=80',
    slug: 'biochemistry',
    email: 'hod.biochemistry@cdu.ac.in',
    recognition: ['UGC'],
    labs: [
      'Molecular Biology Lab',
      'General Biochemistry Lab',
      'Enzymology Lab',
      'Proteomics and Genomics Lab',
      'Food Technology Lab',
    ],
    researchAreas: [
      'Enzyme Kinetics',
      'Insilico Studies & Molecular Modelling',
      'Molecular Docking',
      'Food Processing',
      'Nanotechnology',
      'Microbial Photosynthetic Pigments',
      'Clinical Biochemistry',
    ],
  },
  {
    id: 'biotechnology',
    name: 'Biotechnology',
    shortName: 'BIOTECH',
    description: 'UGC recognized programs in Plant, Animal, Microbial, and Medical Biotechnology.',
    programs: 2,
    image: 'https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&h=600&fit=crop&q=80',
    slug: 'biotechnology',
    email: 'hod.biotechnology@cdu.ac.in',
    recognition: ['UGC'],
    labs: [
      'Plant Tissue Culture Lab',
      'Animal Cell Culture Lab',
      'Molecular Biology and Genetic Engineering Lab',
      'Microbial Biotechnology Lab',
    ],
    researchAreas: [
      'Microbial Biotechnology',
      'Plant Biotechnology',
      'Molecular Biology & Bioinformatics',
      'Genetic Engineering',
      'Agricultural and Environmental Biotechnology',
      'Nanobiotechnology',
      'Medical Biotechnology',
    ],
  },
  {
    id: 'microbiology',
    name: 'Microbiology',
    shortName: 'MICRO',
    description: 'UGC recognized programs with research in Medical, Industrial, and Agricultural Microbiology.',
    programs: 2,
    image: 'https://images.unsplash.com/photo-1576086213369-97a306d36557?w=800&h=600&fit=crop&q=80',
    slug: 'microbiology',
    email: 'lathahod@chaitanya.edu.in',
    recognition: ['UGC'],
    labs: [
      'General Microbiology Lab',
      'Molecular Biology Lab',
      'Immunology Lab',
      'Industrial Microbiology Lab',
      'Medical Microbiology Lab',
      'Agricultural Microbiology Lab',
    ],
    researchAreas: [
      'Medical Microbiology',
      'Antimicrobial Resistance (AMR)',
      'Host-Parasite Interactions',
      'Industrial Microbiology',
      'Food Microbiology',
      'Pharmaceutical Microbiology',
      'Agricultural Microbiology',
      'Bioremediation',
      'Microbial Ecology',
      'Microbial Genetics',
    ],
  },
  {
    id: 'chemistry',
    name: 'Chemistry & Forensic Science',
    shortName: 'CHEM',
    description: 'Programs in Chemistry and Forensic Science with research in Organic Chemistry and Catalysis.',
    programs: 3,
    image: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800&h=600&fit=crop&q=80',
    slug: 'chemistry-forensic',
    email: 'hod.chemfrs@chaitanya.edu.in',
    recognition: ['UGC'],
    yearEstablished: 1991,
    researchAreas: [
      'Synthetic Organic Chemistry',
      'Catalysis',
      'Physical Chemistry',
    ],
  },
  // Agriculture
  {
    id: 'agriculture',
    name: 'Agriculture',
    shortName: 'AGRI',
    description: 'ICAR recognized BSc Agriculture program with focus on sustainable farming and vegetable science.',
    programs: 1,
    image: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&h=600&fit=crop&q=80',
    slug: 'agriculture',
    phone: '9542563650',
    recognition: ['ICAR'],
    yearEstablished: 2021,
    labs: [
      'Horticulture and Plant Breeding Lab',
      'Agronomy and Entomology Lab',
      'Plant Pathology Lab',
      'Soil Science Lab',
      'Shadenet Facility',
      'Field Research Area',
    ],
    researchAreas: [
      'Vegetable Science',
      'Sustainable Farming',
      'Crop Protection',
      'Soil Health Management',
    ],
    fees: {
      'B.Sc Agriculture': '₹1,20,000/year',
    },
  },
  // Management
  {
    id: 'management',
    name: 'Commerce & Business Management',
    shortName: 'MBA',
    description: 'MBA with Eastern Michigan University collaboration, BBA, and B.Com programs.',
    programs: 8,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop&q=80',
    slug: 'management-commerce',
    recognition: ['UGC'],
  },
  // Nursing
  {
    id: 'nursing',
    name: 'Nursing',
    shortName: 'NURSING',
    description: 'INC approved nursing programs preparing healthcare professionals.',
    programs: 3,
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&h=600&fit=crop&q=80',
    slug: 'nursing',
    recognition: ['INC'],
  },
];

export const NEWS_ITEMS = [
  {
    id: '1',
    title: 'Ph.D Admissions Open for Academic Year 2025-26',
    excerpt:
      'Applications are now being accepted for 14 doctoral programs across all departments.',
    date: '2025-01-20',
    category: 'Admissions',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=400&fit=crop&q=80',
    slug: 'phd-admissions-2025-26',
  },
  {
    id: '2',
    title: 'Collaboration with Eastern Michigan University for MBA Program',
    excerpt:
      'New international partnership offers students the opportunity to complete MBA with global exposure.',
    date: '2025-01-15',
    category: 'Partnerships',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600&h=400&fit=crop&q=80',
    slug: 'emu-partnership-mba',
  },
  {
    id: '3',
    title: 'Annual Technical Symposium 2025 Announced',
    excerpt:
      'Register now for our flagship technical event featuring workshops and competitions.',
    date: '2025-01-10',
    category: 'Events',
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=400&fit=crop&q=80',
    slug: 'tech-symposium-2025',
  },
  {
    id: '4',
    title: 'New Hyderabad Campus Now Fully Operational',
    excerpt:
      'State-of-the-art campus in Himayatnagar, Hyderabad offers world-class facilities to students.',
    date: '2024-12-01',
    category: 'Campus',
    image: 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&h=400&fit=crop&q=80',
    slug: 'research-center-inauguration',
  },
];

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Priya Sharma',
    role: 'Software Engineer',
    company: 'Microsoft',
    batch: '2022',
    quote:
      'The faculty at Chaitanya provided excellent guidance that helped me secure my dream job. The practical approach to learning made all the difference.',
    image: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=400&h=400&fit=crop&q=80',
  },
  {
    id: '2',
    name: 'Rahul Reddy',
    role: 'Data Scientist',
    company: 'Amazon',
    batch: '2021',
    quote:
      'The research opportunities and industry connections at Chaitanya opened doors I never imagined. Grateful for the transformative experience.',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop&q=80',
  },
  {
    id: '3',
    name: 'Ananya Patel',
    role: 'Pharmacist',
    company: 'Sun Pharma',
    batch: '2023',
    quote:
      'The Pharmacy department has state-of-the-art labs and dedicated professors who go above and beyond to ensure student success.',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop&q=80',
  },
];

export const RECRUITERS = [
  'Wipro',
  'TCS',
  'Amazon',
  'Tech Mahindra',
  'Infosys',
  'Axis Bank',
  'Capgemini',
  'Reliance Digital',
  'Kun United Hyundai',
  'Aastrin Aviation',
  'Softpath System',
  'SPR Human Capital',
  'Unislink',
  'Cognizant',
  'HCL',
  'Deloitte',
  'Sun Pharma',
  "Dr. Reddy's",
  'Cipla',
  'Aurobindo Pharma',
  'Hetero',
  'Gland Pharma',
];

// Re-export images from Supabase storage
// All images are now hosted on Supabase for better performance
import { SUPABASE_IMAGES } from './supabaseImages';

export const RECRUITER_LOGOS = SUPABASE_IMAGES.recruiters;
export const ACCREDITATION_LOGOS = SUPABASE_IMAGES.accreditation;
export const CAMPUS_IMAGES = SUPABASE_IMAGES.campus;
export const LEADERSHIP_IMAGES = SUPABASE_IMAGES.leadership;
